# Generated by Django 3.0.3 on 2020-05-10 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='important',
        ),
    ]
